### ISSUE TITLE
customize header

### ISSUE THREAD

**Issue by yfsx** [rondinellimorais/ExpandableTableView#1]
hi, thanks for sharing this lib!

i just wanna ask, is it possible to customize header? lets say i wanna add some view / button in the header.
 thanks

**Comment by rondinellimorais** [comment]
Hello @yfsx sorry for the long time no answer.
Yes its possible! You can use something this:

```
class CustomHeader : HeaderView {
}
```
Now you can use a `xib` file to customize you header, or, just create a `xib` for HeaderView class

Let me know if this can help you
