### ISSUE TITLE
Change header after selecting a row in that section

### ISSUE THREAD

**Issue by petec029** [rondinellimorais/ExpandableTableView#2]
How can I change the text in thelabel that I add to the the header view when a row in the table for that section is selected.

I tried the following.  Here is my code 
- (UIView *)tableView:(UITableView *)myTableView viewForHeaderInSection:(NSInteger)section {
  NSLog(@"viewForHeaderInSection");
  HeaderView *headerView = [[HeaderView alloc] initWithTableView:tableView section:section];
  
  headerView.backgroundColor = [UIColor groupTableViewBackgroundColor];
  UILabel *label = [[UILabel alloc] init];
  label.frame = headerView.frame;
  label.tag = 101;
  [label setFrame:CGRectMake(headerView.frame.origin.x+10, headerView.frame.origin.y, headerView.frame.size.width-10, headerView.frame.size.height-1)];
  label.font = [UIFont systemFontOfSize:15.0f];
  label.text = [tableSections objectAtIndex:section];
  
  label.textColor = [UIColor blackColor];
  [headerView addSubview:label];
  
  CGRect sepFrame = CGRectMake(0, headerView.frame.size.height-1, 320, 1);
  UIView *seperatorView =[[UIView alloc] initWithFrame:sepFrame]; seperatorView.backgroundColor = [UIColor colorWithWhite:224.0/255.0 alpha:1.0];
  [headerView addSubview:seperatorView];
  
  return headerView;
  }
- (void)tableView:(UITableView *)myTableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath{
  changeSectionHeader = TRUE;
  selectedVenue = self.nearbyVenues[indexPath.row];
  NSLog(@"selected venue %@ - %@",[selectedVenue title], selectedVenue.category);
  UIView *headerView = [self tableView:self.tableView viewForHeaderInSection:whereSection];
  UILabel *label = (UILabel *)[headerView viewWithTag:101];
  label.text = selectedVenue.title;
  [myTableView deselectRowAtIndexPath:indexPath animated:TRUE];
  }

How do I access the label in the header view to change it's value?

**Comment by rondinellimorais** [comment]
Hello @petec029 sorry for the long time no answer.

Looking your code, I recommend you use custom class header, take a look if this can you help:

```
class CustomHeader : HeaderView {
    @IBOutlet var weak label:UILabel?
}
```
After, you can access you header:

```
(void)tableView:(UITableView *)myTableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath{
CustomHeader *headerView = [self tableView:self.tableView viewForHeaderInSection:whereSection];
headerView.label.text = selectedVenue.title;
[myTableView deselectRowAtIndexPath:indexPath animated:TRUE];
}

```
