### ISSUE TITLE
2 lines in row and remove color in rows

### ISSUE THREAD

**Issue by HideCode7** [rondinellimorais/ExpandableTableView#3]
hi, great job :)

How can I put the rows with 2 lines.
How do I remove the color of the rows.

**Comment by rondinellimorais** [comment]
Hi @HideCode7, thank you!
Sorry for the long time no answer.

_1. How can I put the rows with 2 lines._
This is only a table, you can use method of tableView for insert a new line, but, I recommend just put a new value in the your array data. 

_2. How do I remove the color of the rows._
TableView contains a delegates where you can customize you cell

`tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath)`
`tableView(_ tableView: UITableView, willDisplayHeaderView view: UIView, forSection section: Int)`
`tableView(_ tableView: UITableView, willDisplayFooterView view: UIView, forSection section: Int)`

Please, take a look the documentation.
