### ISSUE TITLE
error on reloading tableView

### ISSUE THREAD

**Issue by unlimitedK** [rondinellimorais/ExpandableTableView#4]
my table gets reload after every 10 sec, and then if I tap on a section, app gets crashes with the error that before update no of rows in a section were different

**Comment by unlimitedK** [comment]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 1.  The number of rows contained in an existing section after the update (0) must be equal to the number of rows contained in that section before the update (297), plus or minus the number of rows inserted or deleted from that section (0 inserted, 295 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).

**Comment by rondinellimorais** [comment]
Hell @unlimitedK sorry for the long time no answer.

I believe that this bug is related with #5 

In any case, I will check in the next days
