### ISSUE TITLE
Swift 3 remove C-Style for Statement

### ISSUE THREAD

**Issue by HideCode7** [rondinellimorais/ExpandableTableView#5]
Hello, it is possible resolve the problem from Swift 3, now C-style for statement has been removed in Swift 3.

This lines of code:

for var i = 0; i < numberOfRows; i += 1 {
            indexesPathToInsert.append(IndexPath(row: i, section: section))
}

And

for var i = 0 ; i < numberOfRows; i += 1 {
            indexesPathToDelete.append(IndexPath(row: i, section: section))
        }

Thank you

**Comment by rondinellimorais** [comment]
Hello @HideCode7 I'm sorry, I will fix this bug in the next days. Sorry for the long time no answer

**Comment by rondinellimorais** [comment]
@HideCode7  do you can change this component yourself? Just request to be contributor for me
