### ISSUE TITLE
IOS 11?

### ISSUE THREAD

**Issue by deezaster** [rondinellimorais/ExpandableTableView#6]
Please ;-)

**Comment by deezaster** [comment]
yeah, i got it. here my solution:

**HeaderView.swift**

```
class HeaderView: UIView {
    :
    
    required init(tableView:UIExpandableTableView, section:Int){
        
      :
      
      // IOS11  
      tableView.estimatedRowHeight = 0;
      tableView.estimatedSectionHeaderHeight = 0;
      tableView.estimatedSectionFooterHeight = 0;
    }
:
```

**Comment by rondinellimorais** [comment]
@deezaster I'm sorry, I will fixe this bug in the next days

**Comment by rondinellimorais** [comment]
@deezaster Sorry for the long time no answer

**Comment by rondinellimorais** [comment]
@deezaster do you can change this component yourself? Just request to be contributor for me

**Comment by rondinellimorais** [comment]
Hello @deezaster, I run the application on IOS 11 and there do not seem to be any problems.

What's the problem you heave?
